### PR TITLE
1092 - TYDE 2 - Add ability to delete connections

### PR DESCRIPTION
**Pull request by EldadZZipori**
## Task Description
When editing a connection, show a Delete button

When connection is deleted, delete that connection from all communities and circles as well.

## Changes

- Add back end functionality to delete a connection in endpoins, endpoins.circle-of-support, and class.circle-of-support
- Add front end functionality to delete a connection only if the connection already exists.

## Issue Linkage
Closes (issue #1092 )
## PR Dependency
Depends on: (PR #1047 )
## Automated Testing
* No automated testing for TYDE

### CODE REVIEW

**Comment by EldadZZipori** [comment]
Failing test is unrelated to this PR. It is caused because the base branch of the base branch is not in-sync with master (node-authoring test fail)

**Comment by odotadot** [comment]
Testing Notes:
Deleting connections works fine when you are deleting from the communities tab - but when you delete from the circles tab it takes a reload for the changes to take place.


https://user-images.githubusercontent.com/34692466/127701398-0a637e11-4bd1-4a5a-b1e9-7daa76905fc1.mp4

**Comment by odotadot** [comment]
I get this error whenever I try to delete any connections now:
image

**Review by odotadot — APPROVED** [review]

**Comment by odotadot** [comment]
Re-tested and deleting connections works perfectly from either community or circles tab. Code looks clean as well.

**Review by wynnset — APPROVED** [review]

**Pull request merged**
