### PR TITLE
736 - Bug fix: control+A selection doesn't work in node modal

### PR DESCRIPTION
**Pull request by seanRong**
- Adds functions to add and remove the dragSelect event listener programmatically
- Modularizes DragSelect to be a utility class
- Uses static functions of DragSelectModular to add or remove event listener when relevant modals open.

### CODE REVIEW

**Comment by shirleywbi** [comment]
Tested. Current behaviour allows select all with Ctrl+A with the media modal open. Should that be the case?
Otherwise, looks good.

**Comment by seanRong** [comment]
Good question, is there a case where text inputs are needed when just the lightbox is open, not the node form itself?
I think gravity forms, but weren't we phasing that out?

**Comment by shirleywbi** [comment]
We'll be phasing Gravity forms out when we create our own built-in replacements so we'll likely still have text inputs.

**Comment by wynnset** [comment]
I think it's best we don't allow node selection if lightbox is open. That would totally be unexpected behaviour from the user's end. I can't see any case in which a user wants to select nodes when they are viewing or editing nodes. It should also be disabled if any other modal (e.g. settings modal) is open. Sorry to change the scope of this PR, but I think this is the right way of doing it.

**Review by shirleywbi — APPROVED** [review]
Tested. Looks good to me.

**Review by wynnset — CHANGES_REQUESTED** [review]
Again, I wonder if we could use Vuex here instead of an event bus so we don't unnecessarily introduce a new mechanism. For example, I imagine we could maintain a Vuex state that indicates whether any modal is open or not. If one is open, then we can disable drag-select altogether? In the future we might add other things that we also might want to be affected by this state.

**Review by shirleywbi — APPROVED** [review]
Tested. LGTM!

**Review by narendrasss — APPROVED** [review]
Code LGTM with the modular changes we discussed!

**Review by wynnset — APPROVED** [review]

**Pull request merged**
