### PR TITLE
848 - Bug fix: thumbnail external link not updating

### PR DESCRIPTION
**Pull request by yungalyx**

### CODE REVIEW

**Comment by wynnset** [comment]
@yungalyx this PR is marked as "waiting for answer" but I do not see a question. Can you please clarify what's going on?

**Comment by yungalyx** [comment]
@wynnset hey, just confirming if this is actually a bug, so im waiting on Bita's response through Asana. I already created the PR for it so I thought it might be better to wait for her response before I close it.

**Comment by wynnset** [comment]
Ok thanks! Next time please leave a comment here to keep the PR updated.

**Comment by yungalyx** [comment]
Issue closed. Bug resulted from user error. i.e, adding an image url into external link instead of thumbnail url link.

**Pull request closed without merging**
