### PR TITLE
Ensure password protection works for tapestries (TYDE)

### PR DESCRIPTION
**Pull request by wynnset**
- Load the assets for tapestry the WP way instead
- Ensure password-protected tapestries are actually password-protected
- Version 2.27.0 bump

### CODE REVIEW

**Comment by narendrasss** [comment]
@wynnset Can you fix these merge conflicts?

**Comment by wynnset** [comment]
@narendrasss done!

**Comment by narendrasss** [comment]
Sorry @wynnset, looks like there's some merge conflicts again. Can you fix them and then I think it's ready to merge.

**Comment by wynnset** [comment]
@narendrasss done!

**Pull request merged**
