### PR TITLE
975 - Fix WP installation for CI

### LINKED ISSUE #975: Fix WP installation for CI

### PR DESCRIPTION
**Pull request by rlnsy**
## Changes
* Includes the WP docker environment variables in the CLI compose config. so it is consistent with the actual WP image. This addresses changes to the default values of these variables in the latest versions of the wordpress image.
## Issue Linkage
Closes #975.
## PR Dependency
Depends on: N/A

### CODE REVIEW

**Comment by rlnsy** [comment]
@wynnset @narendrasss this currently hard-codes the version of the wordpress image we use in docker. It's a hack, but it will fix all of the CI for the time being. The latest versions of the image changed the way that environment variables are loaded into the `wp-config.php` and it's breaking our system. I'm trying to find the root cause rn.

**Comment by rlnsy** [comment]
@narendrasss @wynnset Update: found the root cause. See change description above. This is ready for review and merge in to fix CI problems throughout the project. Note that this same change will need to be done on the `tyde` branch, don't know if we should wait for the official TYDE merge, or create a duplicate PR with `tyde` as the base.

**Comment by wynnset** [comment]
Thanks @rlnsy for finding the issue and fixing this! I think we can add this change as a new commit to the pending tyde merge PR #973 so it gets applied to tyde then. This looks good so I'm going to merge it in right away.

**Comment by wynnset** [comment]
Update: I have committed this change to the tyde merge branch / PR #973

**Pull request merged**
