### PR TITLE
WIP - 23 Create Test data class

### LINKED ISSUE #23: Create class for seed data
Crate a class (TapestryTestData) to put seed data in to test for existing features such as unlock nodes, depth slider

### PR DESCRIPTION
**Pull request by kevinthewebguy**
fixes #23

### CODE REVIEW

**Comment by kevinthewebguy** [comment]
It looks like Andrew is removing the getLinks function (which was to convert hardcoded ids from tapestry.json to the ones from the database. He does not want to replace it with another function to set up the environment. So this issue is blocked until further notice.

**Comment by kevinthewebguy** [comment]
Andrew has agreed to create a function to save tapestry to the database for seed data. Will need to wait for the endpoint to be finished.

**Comment by wynnset** [comment]
As per my conversation with @kevinthewebguy we decided any functionalities related to adding data to the database should be in this class, not in other classes.

**Comment by kevinthewebguy** [comment]
The refactoring of the backend has made the current changes out of date. Will need to redo this from scratch but it is not part of the current sprint.

**Pull request closed without merging**
