### PR TITLE
Don't require video length to be entered 

### PR DESCRIPTION
**Pull request by ItsAdel**
Added automatic video duration detection and got rid of inputs from authoring tool
#471 

Issue: Fix for H5P hasn't been tested and might be incorrect. Hopefully someone else can take over :)

Testing
Create a video node. Enter a video and submit. Ensure proper video duration shows up on the node

Create a hp5 node. Enter h5p with video and submit. Ensure proper video duration shows up on the node

### CODE REVIEW

**Comment by liam-armstrong** [comment]
Tested both uploaded video and H5P, `mediaDuration` is being set correctly

**Comment by wynnset** [comment]
H5P Video duration is not being set correctly for me. Can someone please look into this? The H5P video I selected was not a youtube video, by the way. I had used an uploaded video. This might be why it was working for others.

**Comment by liam-armstrong** [comment]
> 
> 
> H5P Video duration is not being set correctly for me. Can someone please look into this? The H5P video I selected was not a youtube video, by the way. I had used an uploaded video. This might be why it was working for others.

I ran into the same issue with a self-uploaded video. I re-worked the H5P progress in #479 to work with all H5P videos

**Comment by wynnset** [comment]
Closing this as it's addressed in #479

**Pull request closed without merging**
