### PR TITLE
1097 - Automatically enable wordpress debug log on Docker

### LINKED ISSUE #1097: Automatically enable wordpress debug log on Docker

### PR DESCRIPTION
**Pull request by Frozemint**
## Changes
* Add the `WP_DEBUG` parameter into the `docker-compose.yml` file. Note that docker hardcodes [error log output to `/docker.stderr`](https://github.com/schliflo/bedrock-docker/issues/15), so a [workaround](https://carlosguzman.dev/how-to-see-the-error-logs-in-wordpress-with-docker-in-linux/) is still needed. 
## Screenshot
* N/A
## Issue Linkage
Closes #1097 
## PR Dependency
Depends on: N/A
## Automated Testing
N/A

### CODE REVIEW

**Comment by wynnset** [comment]
@Frozemint I noticed that this PR skipped testing. For future reference, please note that all PRs need to go through the workflow stated on Notion, regardless of how small they are.

**Review by EldadZZipori — APPROVED** [review]
This looks good. We should note the cli commands to use and the log commands in this PR and in notion as well(probably under start coding).

**Comment by wynnset** [comment]
> This looks good. We should note the cli commands to use and the log commands in this PR and in notion as well(probably under start coding).

Agreed! @Frozemint could you please add some notes to notion (and maybe readme) to let people know how to debug Wordpress if they are on docker?

**Comment by Frozemint** [comment]
Yeah, the notion page has been updated, along with the readmes and the repo wiki on docker.

**Pull request merged**
