### PR TITLE
804 - Bug Fix: Delete child nodes when links swapped

### LINKED ISSUE #804: Issues deleting child node when links are swapped

### PR DESCRIPTION
**Pull request by shirleywbi**
Closes #804

### CODE REVIEW

**Comment by yungalyx** [comment]
Firstly, I can no longer create the original bug so that's great!
 
1. I can isolate the root node:
Screenshot 2020-10-20 110314

Steps to recreate: 
a. create four sequential nodes (root-> 1 -> 2 -> 3)
b. connect 3 to root
c. delete link between 1 and 2
d. delete link between 3 and root 
e. delete node 1 
notice that 1 and 2 are now isolated from root and trying to delete the isolated child nodes won't work. 

^ assuming that all tapestry nodes must be connected in some way, this might be a big enough issue to warrent it's own PR and I'm not sure if this new issue is within your scope.

**Comment by yungalyx** [comment]
Oops @shirleywbi i think you addressed this issue in #813

**Comment by shirleywbi** [comment]
With that said, @yungalyx, is it ready to test?

**Comment by yungalyx** [comment]
@shirleywbi yes 804 is good for review!

**Review by wynnset — APPROVED** [review]

**Pull request merged**
