### PR TITLE
740 - Bug fix: H5P video in accordion appearing cutoff height-wise

### PR DESCRIPTION
**Pull request by wynnset**
- H5P is no longer cutoff inside accordion
- Remove H5P border by using negative margin

### CODE REVIEW

**Comment by seanRong** [comment]
Tested this, works great.

**Comment by shirleywbi** [comment]
Tested. Video is normal when viewed. However, if you enter full screen and exit full screen, the video is cut off.

**Comment by wynnset** [comment]
Thanks for catching that @shirleywbi! It should be fixed now. I also improved a few other things I found.

**Comment by jaskwong** [comment]
Sometimes minimizing and reopening  the h5p accordion tab multiple times will lead to a cropped video, doesn't happen all the time (tested in incognito and logged in users)
Seems to be due to changes in the value of h5pDimensions.height in setFrameHeight()
image

**Comment by shirleywbi** [comment]
Different issue from Jasmine's but video is still being cropped:
image

**Comment by wynnset** [comment]
@jaskwong please test this as soon as you get a chance (don't forget to pull first)

**Comment by jaskwong** [comment]
I'm still having the same issue as before, when minimizing the video and reopening it within the accordion, I double checked that the branch is up to date

**Comment by wynnset** [comment]
@shirleywbi / @jaskwong could one of you please look into this? I tried so much but cannot replicate either of the reported problems no matter what I do!

**Comment by shirleywbi** [comment]
My earlier issue seems to be resolved but new issue on my end: 
1. Create Accordion (Settings not changed)
2. Create H5P node child

Video works well on Accordion. However, H5P video is playing sound but missing modal:
image

**Comment by jaskwong** [comment]
I’ll look at it tonight, @wynnset what browser do you use?

**Comment by wynnset** [comment]
@shirleywbi thanks for catching that. It's fixed now.

@jaskwong I'm using Chrome on Mac thanks!

**Comment by jaskwong** [comment]
Video I used: https://www.youtube.com/watch?v=qQyhn9DPE00

**Comment by narendrasss** [comment]
Same issue as @jaskwong:

Screen Shot 2020-10-01 at 09 47 21

**Comment by wynnset** [comment]
@narendrasss in the screenshot you attached, everything looks normal.

@jaskwong could you please test this again? I just pushed a possible fix. Thanks!

**Comment by jaskwong** [comment]
Problem seems fixed!

**Comment by narendrasss** [comment]
@wynnset Gotcha, I was under the impression the video should be full-width. If that's the spec then it's good!

**Pull request merged**
