### PR TITLE
817 - Bug Fix: Errors in NodeModal causing infinite load

### LINKED ISSUE #817: Errors in NodeModal causing infinite load

### PR DESCRIPTION
**Pull request by shirleywbi**
Closes #817 

Changes:
- Stopped infinite loading
- Added loading to draft submission

### CODE REVIEW

**Comment by yungalyx** [comment]
trying to upload a vimeo video link with content type = 'video' doesn't seem to prompt a response. Is it possible to tell user that a certain content is not valid instead of preventing a load/publish?

**Comment by shirleywbi** [comment]
@yungalyx Possibly. I'd need to check what kind of response it returns. I had created another Asana ticket for it.

**Comment by shirleywbi** [comment]
@wynnset should we treat above as same scope or separate?

**Comment by wynnset** [comment]
Doesn't really matter. Up to you @shirleywbi

**Comment by shirleywbi** [comment]
@yungalyx I'm going to keep the PR small and for mapping purposes to Asana, will separate the infinite loading from the video issue. Any other bugs you came across or was loading fine? If so, can you change the label?

**Review by wynnset — APPROVED** [review]

**Pull request merged**
