### PR TITLE
873 - TYDE copilot progress completion requires a refresh to show completion

### PR DESCRIPTION
**Pull request by yungalyx**
## Changes
* original issue: progress completion needs page refresh to show completion and unlock
* new issue (fixed): cannot unlock TYDE module nodes
## Issue Linkage
Closes (issue #873 )
## PR Dependency
Depends on: (N/A)
## Automated Testing
* Is automated testing ready for tyde branch? test by 
1. creating two branches of module nodes (each with their respective stage and question set node)
2. lock one module node.. (unlockable by completing the second module node)
3. completing the second node should unlock the first module. no page refresh is needed.

### CODE REVIEW

**Review by shirleywbi — APPROVED** [review]
LGTM

**Review by wynnset — APPROVED** [review]

**Comment by wynnset** [comment]
Can we please test this for copilots? I think this important part of the bug report was overlooked since I don't see anything about copilots mentioned in this PR and therefore not sure if it fixes the original reported bug [on Asana](https://app.asana.com/0/1126491658233864/1190483121003073/f).

**Comment by shirleywbi** [comment]
I think this ticket still needs work. As a copilot acting on admin nodes, viewing the nodes do not seem to update the progress bar even with refresh.

**Comment by odotadot** [comment]
As a copilot, Module 2 (conditioned to unlock when Module 1 is completed) still isn't unlocked when Module 1 is completed (progress bars are all filled for Module 1).

**Comment by wynnset** [comment]
As we move to tyde2, we have decided not to address any more bugs on the old tyde branch

**Pull request closed without merging**
