### PR TITLE
Add support for subaccordions

### LINKED ISSUE #387: Add subaccordions
Allow accordion rows to contain more accordion rows (just 1 level).

### PR DESCRIPTION
**Pull request by narendrasss**
Closes #387

### CODE REVIEW

**Comment by wynnset** [comment]
Hi @narendrasss can you please add a text field that would display before the subaccordion? This should appear in the accordion row for the authoring.

**Comment by narendrasss** [comment]
@wynnset I addressed the changes, but the subaccordions are getting hidden from me.

**Comment by wynnset** [comment]
Accordions are no longer showing (empty lightbox). I'm getting this in the console:
image

**Comment by wynnset** [comment]
A few changes needed:
- Please merge in `master-tyde-06-04-2020`
- Please add ability to reorder subaccordion rows that is now in place for accordions already in `master-tyde-06-04-2020`
- Please make sure the UX improvements we implemented for accordions also apply here (not sure if they are)

Thanks!

**Comment by narendrasss** [comment]
@wynnset I addressed the changes. I'll make a separate PR for the tyde version.

**Pull request merged**
