### PR TITLE
932 - TYDE CoS #3 - Create connections popup

### LINKED ISSUE #932: CoS #3 - Create connections popup

### PR DESCRIPTION
**Pull request by narendrasss**
## Changes
* Add the connections tab to the Circle of Support activity
* Refactor back-end
  * Split up CoS-related endpoints to own module
  * Update CoS class implementation to work with updates

Remaining TODOs:

- [X] Change connections scroll to scroll downwards instead of sideways
- [X] Make connection icons smaller
- [X] Implement search bar

## Screenshot

https://user-images.githubusercontent.com/31267630/106665145-cfa39b80-655a-11eb-891b-9bc30b699cdf.mov

## Issue Linkage
Closes #932 

## PR Dependency
Depends on: #916 

## Automated Testing

N/A

### CODE REVIEW

**Comment by narendrasss** [comment]
@wynnset I spent quite a bit of time trying to get testing to work here but I can't seem to figure it out. I spent about 2 hours doing this so in the interest of time I think I'll defer adding the automated tests — the functionality is simple enough to manually test in my opinion.

**Comment by wynnset** [comment]
Some comments from testing that needs to be addressed:
- Clicking on "Add New" Community doesn't do anything. It should open up the add community modal and when added, it should take the user back to this screen.
- When adding a new connection, if I click on the emoji to change it, the emoji selector pops up, but clicking on a new emoji doesn't do anything.
- Should probably throw an `overflow: hidden;` on the `.cos` wrapper as it's right now showing things outside of that panel
- Wondering - is this responsive? It probably should be! I think it should fill up its container and fit it.
- Change the cursor to `default` on the names of connections in the panel (currently it's the text cursor).
- I feel like the search icon and add (+) icon are still too large. I'd say let's reduce it by another 1/3.
- Can we reduce the spacing between the connections? 
- If there is not enough connections, we should keep the size of this panel at half its hight so there is no empty space at the bottom:  
image

**Comment by narendrasss** [comment]
> Clicking on "Add New" Community doesn't do anything. It should open up the add community modal and when added, it should take the user back to this screen.

This is intentional. The feature is added as part of #951.

> When adding a new connection, if I click on the emoji to change it, the emoji selector pops up, but clicking on a new emoji doesn't do anything.

No issues on my end — tested on both Firefox and Chrome. Were there any console errors? I notice your emojis look different from mine. Could that be an issue?

> Should probably throw an overflow: hidden; on the .cos wrapper as it's right now showing things outside of that panel

Done, thanks.

> Wondering - is this responsive? It probably should be! I think it should fill up its container and fit it.

It's responsive on my end and looks good until about iPad size — 768px. Did you want it to work on mobile as well?

> I feel like the search icon and add (+) icon are still too large. I'd say let's reduce it by another 1/3.
Can we reduce the spacing between the connections?

CleanShot 2021-02-10 at 10 36 08@2x

Is this better?

**Comment by narendrasss** [comment]
@wynnset Made the height more flexible:

https://user-images.githubusercontent.com/31267630/107567660-d3f33880-6b9a-11eb-9031-930507bba45b.mp4

I'm honestly unsure about the search bar, but I figured it wouldn't be the best use of time to refine that more.

**Comment by narendrasss** [comment]
@wynnset Everything aside from the emoji picker not working should be addressed now.

@jaskwong, @shirleywbi, can one of you test the emoji picker on your machine? Not sure if it's an issue only Aidin has since it works fine on my end.

**Comment by wynnset** [comment]
@narendrasss the changes look great, thanks! Let's wait for others to test the emoji picker to see if it works for them. I'm not getting any console errors. Couple of other things: 
- Is this not functional yet? Seems like "Nanda" and "Shirley" come in without me adding them in and it doesn't save when I add more connections.
- I think we should allow the user to edit a connection if they click on that connection.

**Comment by shirleywbi** [comment]
@narendrasss Tested. For me, it's partially working. The selector opens but the face change doesn't render as I'm selecting the different emojis. However, after adding the connection, it shows up as the right one.
ezgif com-gif-maker (3)

**Comment by shirleywbi** [comment]
@narendrasss Also, not sure if this is expected but it seems like if I refresh the page, the emojis disappear.
image

**Comment by narendrasss** [comment]
@shirleywbi @wynnset yup yup I accidentally left a piece of code for testing 😂 should be ok now.

**Comment by shirleywbi** [comment]
@narendrasss The search and filter seem to have disappeared for me: 
image

**Comment by narendrasss** [comment]
@shirleywbi oops, should work now. Thanks for catching that

**Comment by shirleywbi** [comment]
@narendrasss I still seem to be having the same issues as before with the emoji not changing, and refreshing removes the emojis.

**Comment by narendrasss** [comment]
> @narendrasss I still seem to be having the same issues as before with the emoji not changing, and refreshing removes the emojis.

Yeah not sure what's going on there with the emojis not working. I'll look into the refreshing issue.

**Comment by wynnset** [comment]
@narendrasss @shirleywbi I found the issue with the emojis not updating. It's because Wordpress is replacing unicode emojis with images of the emojis and that seems to be causing the dynamic updating of the emojis not to work. I'm not sure how it's working for @narendrasss haha... I've added a piece of code in my commit that disables this when on a tapestry page.

@narendrasss refreshing still clears the connections added. Seems like it's either not saving or not retrieving properly. Otherwise everything else looks good on this PR now.

**Comment by narendrasss** [comment]
@narendrasss Awesome! Thanks for catching that.

**Comment by narendrasss** [comment]
@wynnset @shirleywbi Saving should be fixed!

> I think we should allow the user to edit a connection if they click on that connection.

@wynnset Should this be a part of this PR? I can do it but it would probably take about ~0.5 a day of work.

**Comment by wynnset** [comment]
> @narendrasss narendrasss force-pushed the 932-cos-connections branch from 90ab59e to 2f4f2ec yesterday

@narendrasss I think you overwrote my commit when you force-pushed your commit. Was this on purpose?

**Comment by wynnset** [comment]
I added my changes back in now @narendrasss - let me know if you think we don't need that.

**Comment by narendrasss** [comment]
> I added my changes back in now @narendrasss - let me know if you think we don't need that.

Oh oops! That wasn't intentional. My bad.

**Review by shirleywbi — COMMENTED** [review]
image
The dot only appears upon adding/updating but disappears upon refresh. 
image
* Friend should be in the FRIENDS community but it seems like the community isn't being saved since the blue is not filled.
* Should "Add connection" be "Update connection" to be clear that this is an existing connection?

**Comment by wynnset** [comment]
@shirleywbi I think your comments might be for #950? Let me know as I wanted to merge this PR otherwise.

**Review by shirleywbi — APPROVED** [review]
@wynnset Thanks for clarifying. My comments should be referencing the TODOs in this ticket.

**Comment by narendrasss** [comment]
@wynnset just fyi — I changed the `setTimeout` code you added for the search bar to `this.$nextTick`, which is a feature in Vue specifically for setting callbacks after the DOM has been updated.

https://vuejs.org/v2/api/#Vue-nextTick

**Comment by wynnset** [comment]
> @wynnset just fyi — I changed the `setTimeout` code you added for the search bar to `this.$nextTick`, which is a feature in Vue specifically for setting callbacks after the DOM has been updated.
> 
> https://vuejs.org/v2/api/#Vue-nextTick

Didn't realize nextTick waits for the DOM to get updated. That's perfect!

**Pull request merged**
