### PR TITLE
604 - Fix Docker Plugins Permissions

### LINKED ISSUE #604: Docker Permissions Preventing Plugin Updating

### PR DESCRIPTION
**Pull request by liam-armstrong**
Closes #604 

Change file structure of local environment to use plugins folder in persistent volume rather than bind mount
Fixes ownership issues of files inside container, and allows Apache to write to `/var/www/html` folder
Removes now unnecessary scripts for permission management

Steps to test:
- Launch docker containers
- Reinstall plugins using WP graphical interface and ensure there are no errors
- Also try uploading a file to a tapestry as changes effect the `uploads` folder as well

### CODE REVIEW

**Comment by seanRong** [comment]
Upload is fine, uploaded image displays properly.

Installation via WP's own plugin store as well as uploading .zip all work.

I put in the keys for GF and GF images, but when I'm on a GF node the background is all black. Furthermore when I submit I can't tell what's going on afterwards.  There are render errors in console - I think this has to do with the vue code, and isn't related to the changes made in this PR. 

604-gf-forms-black

If this issue is determined to not be a part of this PR, then looks good to me.

**Comment by wynnset** [comment]
@narendrasss could you test this and let me know if it's ready to be merged in? I notice that you added `needs work` but did not leave a comment to say what needs work. Also, would be great if you could look into Sean's reported issue and let me know if it's related to this PR or not.

**Comment by narendrasss** [comment]
@wynnset I set this as needs work because I wasn't able to install any plugins through the WP dashboard. Oddly enough it works for everyone else.

Do you know what problem this PR was solving in the first place? I don't really have any issues with the current docker workflow.

**Comment by wynnset** [comment]
@narendrasss could you see if running with elevated permissions would allow you to get this PR working please?

**Comment by narendrasss** [comment]
@wynnset I pushed a new PR (#706) that updates the docker config significantly (this was so that cypress can run in github). I didn't have issues installing plugins there, so should this still be considered?

**Comment by wynnset** [comment]
That looks promising. Let's ask Sean to test that and see if he has issues installing plugins on that branch and if it works for him, we can close this PR and delete the associated branch.

**Comment by wynnset** [comment]
Closing this PR as #706 fixes the problem.

**Pull request closed without merging**
