### PR TITLE
Add PHP linter

### LINKED ISSUE #559: Add PHP linter

### PR DESCRIPTION
**Pull request by narendrasss**
Closes #559

* Add PHP linter using the `php-cs-fixer` CLI tool
* Update VSCode settings to recommend `php-cs-fixer` extension
* Add PHP linting to `pre-commit` hook
* Linted all `php` files inside the `tapestry` folder

**Testing**

* Install the `php-cs-fixer` CLI following the instructions from [here](https://cs.symfony.com/)
  * For MacOS users this is as simple as using homebrew: `brew install php-cs-fixer`
* Add some unnecessary whitespace to any `php` file inside the `tapestry` folder
* Try commiting the change
* The linter should run and remove the unnecessary whitespace

### CODE REVIEW

**Comment by wynnset** [comment]
@narendrasss can you please just fix the merge conflicts?

**Comment by wynnset** [comment]
@narendrasss there are still merge conflicts. Maybe your `master` wasn't up to date?

**Comment by narendrasss** [comment]
@wynnset I did it through Github. I don't see any conflicts?
Screen Shot 2020-06-15 at 12 52 57

**Comment by wynnset** [comment]
@narendrasss sorry that was weird. It looks all good now. I even had tried refreshing my page.

**Pull request merged**
