### PR TITLE
1047 - TYDE2 - Move over CoS and change it to open using icon on toolbar

### LINKED ISSUE #916: CoS #1: Design data structure

### LINKED ISSUE #919: Cos #2 - Add endpoints to save data

### LINKED ISSUE #932: CoS #3 - Create connections popup

### LINKED ISSUE #950: CoS #4 - Create communities tab

### LINKED ISSUE #952: CoS #5 - Add smart positioning and responsiveness for communities

### LINKED ISSUE #969: TYDE CoS #6 - Create circle view

### LINKED ISSUE #992: TYDE CoS #7 - Community view onboarding

### LINKED ISSUE #1047: TYDE2 - Move over CoS and change it to open using icon on toolbar

### PR DESCRIPTION
**Pull request by odotadot**
## Changes
-Moved Circle of Support files and components into TYDE2 branch
## Screenshot
image
## Issue Linkage
Closes #1047
Closes #916 
Closes #919
Closes #932
Closes #950 
Closes #952 
Closes #969 
Closes #992  
## PR Dependency
N/A
## Automated Testing
- Can interact with Circle of Support underneath Tapestry

### CODE REVIEW

**Comment by EldadZZipori** [comment]
Everything looks great, all functionality work as it does on the original tyde branch.

**Review by EldadZZipori — APPROVED** [review]

**Comment by wynnset** [comment]
This branch needs to be rebased on the `1061-add-tyde-mode` branch and we need to change the circle of support to show when clicking on the circle of support icon rather than showing right away.

**Comment by wynnset** [comment]
It's now loading as expected, but the page layout is no good:
image
image

I think you have thrown all those elements into a `span` but I recommend you use a `template` so it doesn't actually change the dom - this might fix that issue at least partially. Can you make sure you test this with a multi-content page node and make sure it appears correctly with the padding at the top as well (on the page side menu too) please, @EldadZZipori ?

**Comment by EldadZZipori** [comment]
@wynnset 
Fixed. I also fixed some issues with the styling of page multi-content.
I have a styling dilemma , should the title be centered relative to the page or should the navbar be centered relative to page container?
Also should I push the page-menu down a bit to align with the container or should it stay aligned with the page?
image

**Comment by wynnset** [comment]
@EldadZZipori 
> should the title be centered relative to the page or should the navbar be centered relative to page container?

What if we left-align the title in the container? I don't think we want to centre it. 
> Also should I push the page-menu down a bit to align with the container or should it stay aligned with the page?

Yes please move it down to start where the content starts on the right.

**Comment by EldadZZipori** [comment]
image

**Comment by wynnset** [comment]
I'll review the issue you mentioned and fix it if needed. Thanks!

**Review by wynnset — CHANGES_REQUESTED** [review]
As discussed, code looks good but need to fix these couple of things:
- [ ] Navigating back to the default tab should take me to where I was on that tab, preferably right away and without scrolling or having to wait long
- [x] Clicking on a menu item on the left does not highlight the menu item (fix this here if it's an issue with this branch, otherwise let's open a task to fix it on master later)

**Review by wynnset — APPROVED** [review]

**Review by wynnset — APPROVED** [review]

**Pull request merged**
