### PR TITLE
177 Option for video to open full-screen in browser

### LINKED ISSUE #176: Option for video to open full-screen in browser

### PR DESCRIPTION
**Pull request by anhduc130**
Fixes #176

### CODE REVIEW

**Comment by wynnset** [comment]
Couple of issues I found while testing this:
- The checkbox label in the node edit dialog should read "Open video in full-screen"
- The "X" close button is appearing out of bounds when in full-screen mode
- The video should not overflow out of the window. (i.e. the whole video should be visible no matter what the aspect ratio or screen size is). Any extra space on the side should be filled black.

@narendrasss since you are more of a wiz with css / on the frontend, could you please look into this one?

**Comment by wynnset** [comment]
Please fix the merge conflicts as well.

**Comment by anhduc130** [comment]
The changes I made were mostly in `setupLightbox()` in`tapestry.js`. However, the lightbox is now moved to Vue. After fixing the conflicts, it also removed all the changes I made. This PR should be clean now.

**Comment by narendrasss** [comment]
Fixed a CSS problem that makes the video not show up. Otherwise looks good.

**Pull request merged**
