### PR TITLE
1002 - description word limit includes URLs?

### PR DESCRIPTION
**Pull request by EldadZZipori**
## Changes

- node creation modal counted the description text including the HTML for links and style
- striped the html tags from the description text

## Screenshot
counts-description-text-correct

## Issue Linkage
Closes (issue #1002 )

### CODE REVIEW

**Comment by odotadot** [comment]
Everything looks good, code is clean. Description now saves with hyperlinks in them. All local tests passing.

**Comment by odotadot** [comment]
Actually, this seems to be having the same error as PR 1000: image

**Comment by harry02031** [comment]
Since this still needs work, I will not test it right now

**Comment by EldadZZipori** [comment]
Merged master into this PR. Now works without the unrelated errors.

**Comment by odotadot** [comment]
Unrelated error is resolved. Code looks good, all local tests passing. Succinct solution.

**Review by wynnset — APPROVED** [review]

**Pull request merged**
