### PR TITLE
Fix H5P settings not being saved correctly

### LINKED ISSUE #401: H5P settings are not getting saved

### PR DESCRIPTION
**Pull request by narendrasss**
Fixes #401 

- Includes various refactors to make the code cleaner.

### CODE REVIEW

**Comment by wynnset** [comment]
Sorry, this is still not working for me. I tried watching an H5P video and I changed its speed and turned off its captions and muted it. Then I opened it up and none of those setting were saved. This also happened with another video. Basically settings don't seem to be saving and/or retrieving.

**Comment by wynnset** [comment]
(This is not as high priority as authoring tasks and the merging of master into tyde)

**Comment by wynnset** [comment]
@narendrasss I think I figured out why our machines were not consistent with firing "loaded" event. It's because my H5P video was using an Mp4 uploaded video and I think yours was using a YouTube video. I've now changed it in here to work with either. I've also fix some bugs I found. Feel free to take a look.

**Comment by narendrasss** [comment]
> @narendrasss I think I figured out why our machines were not consistent with firing "loaded" event. It's because my H5P video was using an Mp4 uploaded video and I think yours was using a YouTube video. I've now changed it in here to work with either. I've also fix some bugs I found. Feel free to take a look.

That's strange. I believe my H5P was also from an uploaded mp4. I'll test out your fix.

**Comment by narendrasss** [comment]
@wynnset Nevermind, works great now. Thanks for figuring it out.

**Comment by wynnset** [comment]
@narendrasss do you mind fixing the conflicts on this PR please? I can then merge it in right after.

**Pull request merged**
