### PR TITLE
Add custom audio recorder

### LINKED ISSUE #422: Create custom audio recorder

### PR DESCRIPTION
**Pull request by narendrasss**
Closes #422

- [x] Hook up recorder to backend
- [x] Update authoring tool to a checkbox instead of combobox for audio type answers
- [x] Make sure that audio based entry objects still work as expected

**Testing**

- Run `npm install` to install the new recorder polyfill required for older browsers
- Create a new quiz with an audio recorder as one of the answer types
- Open the quiz then record something
- The same recording should appear when the page is refreshed and the quiz reopens

### CODE REVIEW

**Comment by liam-armstrong** [comment]
image

When this branch loads, there seems to be a component missing or mistakenly imported. Is there a missing merge?

**Comment by narendrasss** [comment]
> image
> 
> When this branch loads, there seems to be a component missing or mistakenly imported. Is there a missing merge?

Sorry, make sure to run `npm install` first. I'll add it to the testing instructions.

**Comment by liam-armstrong** [comment]
image

When I press the record button, nothing happens and I get this error in the console.

**Comment by liam-armstrong** [comment]
image

Icons aren't centered on the buttons

**Comment by narendrasss** [comment]
@liam-armstrong I can't replicate in either Chrome or Firefox. Which browser were you using?

**Comment by liam-armstrong** [comment]
> @liam-armstrong I can't replicate in either Chrome or Firefox. Which browser were you using?

Firefox 75.0 (64-bit). I gave it another shot and it asked for permission to use my microphone, which allowed me to record audio properly. The console error still occurred though. 

Also, after recording audio and reloading, I get an error loading user progress and the app won't start. 
image

 All these issues might be my machine - maybe @ItsAdel could give it a try and see if these are isolated incidents.

**Comment by ItsAdel** [comment]
The first time you try to record an audio in the node you just created, you get this in console.
image

Console shows the bottom image when I hit done after finishing recording to submit it.
image

-----------------

Otherwise, the recorder seems to be functioning correctly for me and replays recorded audio upon reopening the quiz

**Comment by wynnset** [comment]
This is looking really good! Couple of issues:
1. When you go back to an activity where you already recorded an audio, it should show you your recording, not an audio recorder (user could re-record if they want to at that point)
2. When I try to show my answer as a follow up before another question, it says you have not done that activity, even though I answered it using audio.

**Comment by narendrasss** [comment]
@wynnset I can't replicate this. Can you try again to see if it happens for you?

**Comment by narendrasss** [comment]
@wynnset Actually I'm going to assign this back to me to remove all of the code in `H5PIframe` relating to the audio recorder.

**Pull request merged**
