### PR TITLE
738 - Public users should not be able to add or edit

### LINKED ISSUE #737: Unable to add a connection as a user

### LINKED ISSUE #738: Public user can be given permission to add or edit, but cannot actually add

### PR DESCRIPTION
**Pull request by narendrasss**
Closes #738 

This PR removes support for node creation by public users. Specifically:
- The add button will now _always_ be hidden for public users, regardless of the permission set in the node
- The "add" permission checkbox for public users is now disabled, so authors won't be able to set this permission for future nodes
- For current nodes, the add permission is stripped when the node is loaded in

### CODE REVIEW

**Comment by shirleywbi** [comment]
Tested!
737: Connections are stable.
738: Can create connections between child and grandchild nodes and view other nodes.
Removal of support for node creation by public users: Looks good.

**Comment by shirleywbi** [comment]
Does anything need to be changed server-side in terms of permissions?

**Comment by wynnset** [comment]
Sorry to completely change the scope of this PR, but I feel like it's incomplete without everything else and we might as well address the root issue here. Please take a look at the Asana issue for this to understand and implement the full requirements.

**Comment by yungalyx** [comment]
Public can delete links between nodes! 😱 This destroys access to other nodes. This affects the tapestry from admin side and doesn't fix on page reload either. Caught a big bug here!

**Review by shirleywbi — COMMENTED** [review]
Issues:
* If there's an existing node where public has permissions to read and (add or edit), it unchecks read in the Permissions Table when updated.
* If there's an existing tapestry where public has permissions to read, add, and edit, the table keeps add and edit checked and does not allow you to uncheck.

All other behaviour looks good.

**Review by shirleywbi — CHANGES_REQUESTED** [review]
New commit fixed existing individual nodes but looks like there's still an issue with the main settings permissions.

If I have a Tapestry with existing defaults set to allow Read/Add/Edit permissions for Public, the Tapestry still shows that the default is Read/Add/Edit. This is also the case if I create a new node.  
image

If I try to change the Tapestry Settings by deselecting Add/Edit, I can't reselect them.
ezgif com-gif-maker

**Review by shirleywbi — APPROVED** [review]
Looks good to me!

**Comment by wynnset** [comment]
When "Authenticated" is checked for either the "Add" or "Edit" column, the checkboxes below should become disabled. It doesn't make sense to allow **_ALL_** authenticated users to have a certain permission, but then **_at the same time_** not allow a particular role to have that same permission. 

image

**Comment by jaskwong** [comment]
@wynnset I think that's a separate issue ("Clicking on "Add" or "Edit" for "Public" or "Authenticated" rows doesn't disable permissions under it" on asana), this PR is just for preventing public users from adding/editing and also preventing unauthorized users from deleting links

**Review by wynnset — APPROVED** [review]

**Pull request merged**
