### PR TITLE
837 - Bug Fix: Hide disjoint accordion nodes

### LINKED ISSUE #837: Prevent 3-level accordion

### PR DESCRIPTION
**Pull request by shirleywbi**
## Changes
* Hide disjoint accordion nodes
* Add cypress tests for visible descendants and adding node to subaccordion row
## Issue Linkage
Closes #837
## PR Dependency
Depends on: N/A
## Automated Testing
* Added Cypress: "Accordion should not show descendants to subscriber."
* Added Cypress: "Accordion should not be able to add a node to subaccordion row if accordion row is not an accordion"

### CODE REVIEW

**Comment by yungalyx** [comment]
@shirleywbi looks good! The linked update on Slack through Asana was helpful in letting me figure out what to test, thanks for that!

**Review by wynnset — APPROVED** [review]

**Comment by wynnset** [comment]
Seems like one of the tests is failing.

**Comment by wynnset** [comment]
The test is failing (flaky) on #871 as well.

**Comment by shirleywbi** [comment]
@wynnset Looks like the test is also flaky on master. The node is occasionally created partially off-screen so Cypress doesn't think it can click it. Would you like me to fix it in this PR or create a new one?

**Comment by wynnset** [comment]
Can you create a task to fix that on Asana and prioritize it, please, since it's affecting everything? I'll merge this PR in.

**Pull request merged**
