### PR TITLE
789 - Bug fix: Links are displaying in the wrong place when dragging

### LINKED ISSUE #789: Links are displaying in the wrong place when dragging to add a new link

### PR DESCRIPTION
**Pull request by narendrasss**
Fixes #789

### CODE REVIEW

**Review by wynnset — APPROVED** [review]
Thanks @narendrasss

**Comment by wynnset** [comment]
@jaskwong could you give this a quick test?

**Comment by jaskwong** [comment]
Tested, works great!

**Comment by wynnset** [comment]
@jaskwong don't forget to change the label on the PR to `ready for review` to help me know it's been tested :)

**Pull request merged**
