### PR TITLE
739 - cannot select new nodes

### PR DESCRIPTION
**Pull request by seanRong**
Utilizes bus to add all new nodes to selectables array, also refactors TapestryApp.vue to support this implementation.

### CODE REVIEW

**Comment by shirleywbi** [comment]
Tested. No issues found.

**Comment by wynnset** [comment]
@seanRong / @narendrasss is it possible to use Vuex instead of an event bus for this? I prefer not to add an event bus to the app if we can use Vuex.

**Review by shirleywbi — APPROVED** [review]
LGTM. Working great. Also covers [736](https://github.com/wynnset/tapestry-wp/pull/749/files).

**Review by narendrasss — APPROVED** [review]
Code LGTM!

**Pull request merged**
