### PR TITLE
826 - Bug fix: Mispositioned media buttons in Safari

### LINKED ISSUE #826: Media button appears out of place in Safari

### PR DESCRIPTION
**Pull request by narendrasss**
Closes #826 

**Changes**

- [X] Change media buttons to not use `foreignObject` (inconsistent behaviour in Safari)
- [x] Change `TapestryIcon` implementation to work when embedded in SVG

### CODE REVIEW

**Comment by wynnset** [comment]
Potential resource: https://github.com/FortAwesome/vue-fontawesome

**Comment by seanRong** [comment]
ezgif-3-6dac175be7e9
Take a look at this - the buttons are somewhat difficult to click on. It seems like not the entire circle is targetable.

**Comment by seanRong** [comment]
Screen Shot 2020-11-02 at 9 08 00 AM
Screen Shot 2020-11-02 at 9 08 52 AM
Not sure what happened :( icons are just gone now but they're pretty easy to click now.

**Comment by wynnset** [comment]
@seanRong I can't replicate the issue you are having. Can you investigate why it's happening for you? Maybe you need a hard refresh or something?

**Comment by seanRong** [comment]
I don't really know how, but it has since fixed itself. Maybe the master merges did something?

**Pull request merged**
