### PR TITLE
1119 - Activities do not fit the lightbox on tyde2

### PR DESCRIPTION
**Pull request by EldadZZipori**
## Changes
Sets the media-wrapper div to have width:100%
## Issue Linkage
Closes (issue #1119 )
## PR Dependency
Depends on: (N/A)

### CODE REVIEW

**Comment by wynnset** [comment]
@EldadZZipori is this working on master? Is the issue only with tyde2?

**Comment by wynnset** [comment]
As we discussed, once done with higher priority issues, we should look and see how come this is not an issue on master even though the code is the same (or maybe the latest master is not pulled into tyde2)

**Comment by EldadZZipori** [comment]
I looked locally and it seems that master is not merged into tyde2

**Comment by wynnset** [comment]
Ok, so if we merge master into tyde2 this will be fixed? Have you tested it @EldadZZipori ? If so, we can close this PR.

**Comment by EldadZZipori** [comment]
Yes right. On master, it is working. Closing this PR

**Pull request closed without merging**
