### PR TITLE
769 - creating slack mention workflow

### PR DESCRIPTION
**Pull request by yungalyx**

### CODE REVIEW

**Comment by yungalyx** [comment]
I just added some workflow script for the github->slack notifier. It doesn't conflict with any other scripts. As of right now, only Shirley, Aidin, and I will recieve personal slack notifications if this works as intended.

**Review by shirleywbi — APPROVED** [review]
Workflow looks fine to me as per: https://github.com/marketplace/actions/github-mention-to-slack
SLACK_WEBHOOK_URL will need to be added to the secrets?

**Comment by wynnset** [comment]
@yungalyx does this need to be merged first before we can test it? Or otherwise not sure how we can test it before merging it in? Can you clarify?

**Comment by yungalyx** [comment]
@wynnset Hi, I look into it! I'm pretty sure the workflow script can't be tested unless it's actually part of the github repo.

**Comment by yungalyx** [comment]
@wynnset Looks like the GHA workflow requires creating a slackbot and authorizing certain endpoints by admin. I don't have access to those and I wouldn't want to accidentally break anything. Here's a third party automation that does the same thing: https://zapier.com/apps/github/integrations/slack/11499/get-direct-messages-on-slack-for-new-github-mentions

As long as we're under 750 mention converts a month, it's free!

**Review by wynnset — APPROVED** [review]

**Pull request merged**
