### PR TITLE
991- Create "Question" node type with audio and text answer types

### LINKED ISSUE #991: Create "Question" node type with audio and text answer types

### PR DESCRIPTION
**Pull request by shirleywbi**
## Changes
* Add question node content type (similar to "Activity" except it handles a single question)
    * *QuestionForm*         
        * Add ability to toggle text and audio response, show a previous answer before an activity, and customize confirmation page
            * Previous answers are cross-compatible between activity and question nodes.
            * Options are stored in `node.typeData` as 
image
        * For a text response, allow selecting multi-line vs. single line. Single line allows setting an optional placeholder.
        * Add error handling for empty question text and unselected response type
    * *Lightbox*
        * Shows activity screen without navigation
        * Update activity screen to use textarea and input for question nodes, based on form selection. Responses are saved under `quiz[0].entries` as `textId: { [formId]: "response" }` to make it similar to how audio and gravity forms are structured.
* If the current node is not an "activity", hide "Activity" from Content Type dropdown
## Screenshot
ezgif com-gif-maker (12)
## Issue Linkage
Closes #991 
## PR Dependency
Depends on: N/A
## Automated Testing
* Able to complete with an text-based answer
* Able to complete with an audio-based answer

### CODE REVIEW

**Comment by EldadZZipori** [comment]
I believe this should be checked on another system in addition to mine as well.

TODO:
1. Fix submission saving of text and audio response to question. 
- Currently the submission does not save and if user selected to display the previous answer it shows that no previous answer was submitted. 
- Happens whether login or not
- No console alerts appear
ezgif com-gif-maker

2. At the moment, the tests don't always pass because the "Submitting..." screen disappears too quickly.
- This is probably because the submission is not saved but still should be tracked
- Does not always happen, run the test alone and with all the other tests as well.

3. I think question testing should be more comprehensive.
- Test "Previous user answer"
- Test "Confirmation Page Customization"

**Comment by harry02031** [comment]
Things I noticed when reviewing this PR
1.
The "Show Answer To A Previous Activity First" functionality does not work currently. 

https://user-images.githubusercontent.com/30706624/118183652-31439380-b3ef-11eb-8ba2-19531dd61a88.mov

All question type nodes are unable to submit their answers properly and store it in the backend. Both the answers inputted by the user in audio mode or in text mode does not get submitted properly to the backend and so, the "Show Answer To A Previous Activity First" functionality always outputs "You haven't done the previous activity yet".

2.
The testing passes fine by me(pther than the occassional lightbox failure, but restarting cypress made the test run smoothly for me), but I would also suggest having a test that tests the user answer to a previous answer once that problem(see above) have been fixed. The only thing that might be troubling that keeps on happening in this question.spec.js is shown in the screenshot below, it seems when the video is forwarded to 1 hour by the async tick function, the subsequent post method is being aborted 73 times. However, this does not affect the overall unit test as both test(video and text response to the question) passes in the end.
Screen Shot 2021-05-13 at 2 18 18 PM
Screen Shot 2021-05-13 at 2 18 36 PM

**Comment by wynnset** [comment]
Hi @harry02031 

Regarding your first point, I was looking at the video you posted and I noticed you didn't select an activity to show the answer to when setting up the authoring: 
image

Where it says "Then show user the answer to the following activity:" you are supposed to select an activity to show the answer to. To clarify, it's NOT supposed to show the answer to the current activity. There is currently no way to view the answer to an activity (except if you check the database). A future task will address that.

Maybe you can mention the issues you are experiencing with the testing in our standup to see if someone else can verify.

Also, since this PR doesn't have an author anymore, can you please inherit it as the new author?

**Comment by harry02031** [comment]
> Hi @harry02031
> 
> Regarding your first point, I was looking at the video you posted and I noticed you didn't select an activity to show the answer to when setting up the authoring:
> image
> 
> Where it says "Then show user the answer to the following activity:" you are supposed to select an activity to show the answer to. To clarify, it's NOT supposed to show the answer to the current activity. There is currently no way to view the answer to an activity (except if you check the database). A future task will address that.
> 
> Maybe you can mention the issues you are experiencing with the testing in our standup to see if someone else can verify.
> 
> Also, since this PR doesn't have an author anymore, can you please inherit it as the new author?

Hey @wynnset, my bad, but yes the previous answer functionality is working properly now after setting "Then show user the answer to the following activity:".

**Comment by harry02031** [comment]
Code looks good to me, as well as functionality and testing have been double checked.

**Review by harry02031 — APPROVED** [review]

**Comment by wynnset** [comment]
Just a few visual updates needed:
- [ ] The question panel currently seems to have a grey background going 2/3 of the way down and the rest underneath is appearing as black. This should be fully the same color.
- [ ] The answer options should be centered and minimally apart (10-20px)  
  image
- [ ] When submitting, the loading icon / animation should not appear at the top like this:
  image

**Comment by wynnset** [comment]
Found a major bug:
- [ ] Logging in as a different user, I see the answers I did while I was logged in with a completely different user. This shows a major data issue: 
  image 
  image
- [ ] Not sure if this is cause by the same issue, but the text answer type has a checkmark which indicates the user has done it, even though I didn't:  
  image

**Comment by wynnset** [comment]
@harry02031 could you please look into the latest bug I found above?

**Comment by wynnset** [comment]
I've looked into the usage of "Activity" node type on production and it is not being used outside of tyde. As a result, we can completely remove activity and any activity-related code. Note that question nodes should **not** use the existing activity / quiz data structure or code, so we can rewrite it from scratch, making sure to have a clean data structure for it and minimizing the usage of unnecessary fields.

This PR now requires a major refactor (or even a different branch from scratch) to address these issues and the outstanding issue mentioned above (which should become much easier to resolve once this refactoring is complete)

**Comment by wynnset** [comment]
Closing this PR as it's superseded by #1043

**Pull request closed without merging**
