### PR TITLE
730 - Bug fix: Tapestry Depth setting showing incorrect max depth

### LINKED ISSUE #730: Tapestry Depth setting showing incorrect max depth

### PR DESCRIPTION
**Pull request by seanRong**
Closes #730 
Moves bus listener from mounted hook to created hook for SettingsModal so it may actually receive the emits from maxDepth changing.

### CODE REVIEW

**Comment by shirleywbi** [comment]
Test Findings:
- When you select a default depth less than max depth, refreshing the page results in the max depth.
- Unable to select a default depth less than the max depth.

**Comment by seanRong** [comment]
Thank you Shirley, has been fixed

**Review by shirleywbi — COMMENTED** [review]
Potential issues I'm coming across:
- Since the default is set to 3, shouldn't I be seeing all the nodes in this image vs. only the root?
730-Default_Depth
- If I have an arrangement of nodes like this:
730-Max_Depth

1.  Go to the depth slider. It shows max-depth = 4
2.  Click a different depth (e.g., 2).
3.  Slide back to the end of the slider. It shows max-depth = 3

**Comment by narendrasss** [comment]
@shirleywbi I merged in the latest master changes and those issues don't seem to be happening anymore. Can you try again?

**Comment by shirleywbi** [comment]
Clarification: How should depth be calculated? Is it based off the root node or is it the longest path? Currently, it is based off the root node.

Nonetheless, still getting issues with default depth = 3. This is one long chain of [3 nodes][root][6 nodes]
image

**Comment by seanRong** [comment]
For that picture in particular, it looks fine, unless there is more than 1 node being hidden in the grandchildren. 

Max depth has always been distance to furthest node from currently selected root node

**Review by shirleywbi — APPROVED** [review]
In that case, thanks for clarifying. It looks good to me.

**Review by wynnset — APPROVED** [review]

**Pull request merged**
