### PR TITLE
800 - Ability to add/edit all nodes as a contributor unintentionally causing nodes to delete 

### PR DESCRIPTION
**Pull request by yungalyx**

### CODE REVIEW

**Comment by yungalyx** [comment]
https://app.asana.com/0/1126491658233864/1194908912828384
Bita has a video clearly describing the issue in Asana!

**Comment by yungalyx** [comment]
note: this bug is due to logging in as two seperates users at the same time from seperate tabs. Glitches are visual only and clear on refresh. not sure if there's a workaround for this within Tapestry scope...

**Comment by wynnset** [comment]
Hi @yungalyx what is your question for me here?

**Comment by wynnset** [comment]
Ok, I just saw your Asana comment and replied. I've messaged Bita to ask her to check to see if she is still able to reproduce this issue. Let's close this for now and we can reopen if we find she is still experiencing it. Closes #800

**Comment by wynnset** [comment]
By the way @yungalyx please do not forget to include the closing keyword in your PR descriptions - it's essential. Feel free to review the Notion page again if you are unsure about the PR process.

**Pull request closed without merging**
