### PR TITLE
Allow authors to select and move multiple nodes together

### LINKED ISSUE #411: Allow authors to move groups of nodes together
- Drag selection box
- Ctrl/Cmd click

### PR DESCRIPTION
**Pull request by narendrasss**
Closes #411

- Add node selection using `cmd`, `ctrl` and `shift` keys
- Add node selection using a selection box using the `DragSelect` library
- Select all nodes using `cmd+A`
- Clear selection by either clicking outside a node or pressing the `esc` key
- Selected nodes are currently highlighted orange, but can be easily changed if need be

**Testing**

- Go to a tapestry that you've previously made
- Select around using the commands above

### CODE REVIEW

**Comment by wynnset** [comment]
This looks great, @narendrasss - the only thing is, is there a way to mark which nodes are selected? Either after selection is complete or, even better, when you are dragging the box to select nodes.

**Comment by narendrasss** [comment]
@wynnset I'm not sure what you mean. Right now selected nodes are highlighted orange - I can change that though if you want it to look different.

**Comment by wynnset** [comment]
Couple of things:
- It doesn't seem to work if it's using an icon like on TYDE with the progress bar, title, and media button hidden. 
- When dragging to select, if I drag back, it doesn't unselect.

**Comment by wynnset** [comment]
Looks and works great now thanks @narendrasss ! I just changed the highlight color to the Tapestry blue color to be consistent.

**Pull request merged**
