### PR TITLE
553 - Allow author to set default tapestry depth

### LINKED ISSUE #553: Allow authors to set a default Tapestry depth

### PR DESCRIPTION
**Pull request by narendrasss**
Closes #553 

Adds a default depth setting that is configurable using a depth slider similar to the one that is already implemented.

### CODE REVIEW

**Comment by liam-armstrong** [comment]
Works well, saves setting and reapplies on refresh.

**Comment by wynnset** [comment]
Tapestry is not loading on this branch and getting a bunch of console errors:
image

**Comment by wynnset** [comment]
The original depth slider is not showing the correct depth:
image
image

**Comment by wynnset** [comment]
@narendrasss I made a change to allow setting depth to 0 as it is important for disabling depth, FYI.

**Pull request merged**
