### PR TITLE
1004 - Error alerts in node modal should scroll the view when displayed

### PR DESCRIPTION
**Pull request by EldadZZipori**
## Changes
- Changed the position of the error-wrapper to sticky with a small z-index to overflow over all other elements
## Screenshot
* This is a space to include a screenshot or GIF if this is a frontend change. Delete this section if this is not a frontend change.
## Issue Linkage
Closes (issue #1004 )
Screenshot from 2021-05-06 09-24-41

### CODE REVIEW

**Comment by odotadot** [comment]
Everything looks good, code is clean. All local tests passing, except for the  1) External link should be able to add an external link using the url input cypress test as mentioned above as being flaky.

**Comment by odotadot** [comment]
Original issue is resolved. Everything looks great, all local tests pass. However, still same error with PR 1000 and 1002 (opening accordion nodes will result in these errors. Errors don't happen on master branch):
image

**Comment by EldadZZipori** [comment]
Merged master into this PR. Now works without the unrelated errors.

**Comment by odotadot** [comment]
Correction looks good and all local tests pass.

**Review by wynnset — APPROVED** [review]

**Pull request merged**
