### PR TITLE
653 - Integrate Cypress to run automatically on Github

### PR DESCRIPTION
**Pull request by narendrasss**
(This is a test PR)

### CODE REVIEW

**Comment by liam-armstrong** [comment]
Some of the tests aren't passing, but the infrastructure for running the tests is up and going, and won't impact local dev environments so this is good to merge into #509 AFAIK.

**Comment by narendrasss** [comment]
Thanks for your hard work on this @liam-armstrong! I think we can get around the link preview issue by using [secrets](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets) and attaching the API key there.

I think @wynnset is the only one who can set this up however so we can talk about it more in tomorrow's standup.

**Comment by wynnset** [comment]
We should deal with the link preview issue as per @narendrasss above and also install gf using the gravityforms cli (which requires wp-cli as well): https://wordpress.org/plugins/gravityformscli/

**Comment by narendrasss** [comment]
@liam-armstrong Can you look into integrating the gravity forms cli when you get a chance?

**Comment by wynnset** [comment]
`LINK_PREVIEW_API_KEY` and `GRAVITY_FORMS_API_KEY` secrets have been added. I had to choose different secret names because only uppercase characters and underscores are allowed so CamelCase did not work, so those will need to be updated.

**Comment by narendrasss** [comment]
Going to keep this up for the time being but might be replaced with #705.

**Comment by narendrasss** [comment]
Gonna close this in favor of #707.

**Pull request closed without merging**
