### PR TITLE
536 - Show a sidebar when selecting a node

### LINKED ISSUE #536: Show a sidebar when selecting a node

### PR DESCRIPTION
**Pull request by narendrasss**
Closes #536 

**Changes**

- Adds a sidebar on the side of a Tapestry that shows information on the currently selected node
- Sidebar contains the node title, description, copyright and references information
- Sidebar is responsive and should look good on all screen sizes including mobile
- Reposition node modal so that sidebar is always visible when open

**Testing**

Load a Tapestry, the sidebar should be visible on the right side and span the height of the screen.

- Click on the information icon and the sidebar should slide open with the information icon highlighted green
- Click on the arrow in the middle and the sidebar should close
- Click on the view button should open the lightbox for that node
- Click on the edit button should open the node modal with that node loaded in
  - The node modal should be positioned to the left of the sidebar and not cover it **unless your screen is less than 1280 pixels wide**

Create a node with a very long copyright and reference list (long enough that the sidebar has a scrollbar).

- Select the node, then open the sidebar
- Scroll down. When you reach the copyright title, the green highlight should move to the copyright logo
- Click on the information icon. The sidebar should scroll back up to the node title and description and the information icon should now be highlighted.

Create a node without public edit permissions.

- Open the Tapestry in incognito mode (or log out)
- Click on the node without edit permissions and open the sidebar
- The edit button on the top right corner should not be visible

Shrink your browser so it's <500px wide.

- The sidebar should cover the entire window and the icons should appear at the bottom

### CODE REVIEW

**Comment by narendrasss** [comment]
The basic functionality is completed - waiting on the completed mockups from Simi.

**Comment by liam-armstrong** [comment]
Tested and works well, especially the mobile version! One small change we could consider is that clicking the information icon again should also close the sidebar. It's slightly unintuitive to have two buttons for open and close

**Comment by wynnset** [comment]
This looks great thanks. Just a few changes / fixes required:
- Please limit the width of the sidebar to 20vw. I find it too large as-is
- Please put the title on its own line and the view/edit buttons on a separate line from the title
- Can you please make the View and Edit buttons appear more like buttons like the rest of the buttons we use (e.g. in the node modal)
- Currently, the "i" icon on the menu has its background highlighted green when it's selected. Can we change this instead to highlight the icon itself and leave the background as-is? Also, please use an existing color like the light blue color we use to highlight it. Can you also make it a bit smaller? It looks too big.
- Currently, the drag box used to select nodes in the tapestry extends into the sidebar, but it shouldn't. That's part of the tapestry and doesn't make sense for it to go outside of the tapestry area
- When I reduce my browser size, the nodes seem to become unselectable. Clicking on nodes doesn't do anything

I am also not too sure about the thick grey line that appears. I am not a huge fan of that design. I feel that it would look much nicer if the whole sidebar is one solid background (either all light or all dark). We could add a shallow box shadow perhaps to the left to separate it. Feel free to message me to chat more about this part or the visuals in general.

**Comment by wynnset** [comment]
Here's a _rough_ visual - feel free to update a bit as needed:
image

**Comment by narendrasss** [comment]
> Code review: Seems like a lot of unrelated refactoring was done in this PR. I'm not against it, but question why it was done in this PR. Is this a mistake or is that what's meant to be?

If you're referring to the `node-modal` component being moved around, it was a necessary change in order for the sidebar to be able to open the node modal.

**Comment by wynnset** [comment]
> > Code review: Seems like a lot of unrelated refactoring was done in this PR. I'm not against it, but question why it was done in this PR. Is this a mistake or is that what's meant to be?
> 
> If you're referring to the `node-modal` component being moved around, it was a necessary change in order for the sidebar to be able to open the node modal.

What about the linting/formatting of random files? You can see what I mean if you look at the file changes

**Comment by narendrasss** [comment]
Oh you're right. I can quickly revert those changes.

**Comment by narendrasss** [comment]
@wynnset Should be good now.

**Comment by wynnset** [comment]
Waiting for the base branch to get merged first. It'll have the text formatting options and we'll need to test that first with this branch before merging it in.

**Comment by codygagnon** [comment]
Works great! A few issues/questions:

1. Maybe we should add some text under the About heading if the description field is blank? Something, like "This node has no description." Otherwise users might be confused and think that About is clickable.
1. The info and copyright icons are highlighted white when selected, not green.
1. After closing the edit node modal, the edit button still appears as if selected (see image below). 

image

**Comment by narendrasss** [comment]
Waiting on #539 to get merged in before merging this in.

**Comment by wynnset** [comment]
image

Can we please have an icon beside the link to indicate that the license is a link? Maybe an icon that indicates this is a link and it will open in a new window. Right now, it's hard to know that it is a link.

**Comment by narendrasss** [comment]
@wynnset I changed it to look like this:

Screen Shot 2020-08-18 at 10 00 43

Let me know what you think!

**Comment by wynnset** [comment]
> @wynnset I changed it to look like this:
> 
> Screen Shot 2020-08-18 at 10 00 43
> 
> Let me know what you think!

This looks great!

**Pull request merged**
